### ISSUE TITLE
wasdev links are bad

### ISSUE THREAD

**Issue by dlp01** [ibm-cloud-docs/java#5]
On this page: https://cloud.ibm.com/docs/java?topic=java-liberty

The link for this phrase 
```WebSphere Liberty is a commercial version of Open Liberty. ```
is https://developer.ibm.com/wasdev/

WASDEV is no longer active.  It got moved recently.  It might be good to confirm with Alasdair Nottingham, but I believe it should be https://www.ibm.com/cloud/websphere-liberty now

**Comment by christoc-ibm** [comment]
The link is now fixed.
